spring.application.name=device-management

spring.datasource.url=jdbc:postgresql://localhost:5433/device_management
spring.datasource.username=nehaashwin
spring.datasource.password=prep_project

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true