spring.application.name=device-management

spring.datasource.url=jdbc:postgresql://localhost:5432/device_management
spring.datasource.username=nehaashwin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true